### ISSUE TITLE
hlx shows ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#1053]
```
$ node  --trace-warnings index.js --version
(node:67348) ExperimentalWarning: The fs.promises API is experimental
    at Object.get (fs.js:1841:17)
    at verifySchema (~/codez/helix/project-helix/modules/helix-cli/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1091:33)
    at Map.set (~/codez/helix/project-helix/modules/helix-cli/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:1119:5)
    at Object.<anonymous> (~/codez/helix/project-helix/modules/helix-cli/src/git-utils.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by tripodsan** [comment]
see https://github.com/isomorphic-git/isomorphic-git/issues/771

**Comment by stefan-guggisberg** [comment]
[isomorphic-git](https://github.com/isomorphic-git/isomorphic-git/) intentionally makes use of `fs.promises`, see https://github.com/isomorphic-git/isomorphic-git/pull/730.

I don't think they're eager to refactor their `fs` plugin using e.g. `fs-extra`, just to get rid of a single temporary warning.

Running `node index.js --version` on Node 10.x just produces a single warning line on the console:
```
$ node index.js --version
(node:33330) ExperimentalWarning: The fs.promises API is experimental
4.9.2
```

IMO that's acceptable, the more so as it is only temporary. The warning will disappear with newer Node versions.

If we really want to get rid of this warning we could so using a simple hack:

```diff
--- a/src/git-utils.js
+++ b/src/git-utils.js
@@ -18,6 +18,8 @@ const fse = require('fs-extra');
 
 const { GitUrl } = require('@adobe/helix-shared');
 const git = require('isomorphic-git');
+// eslint-disable-next-line global-require
+delete require('fs').promises;
 git.plugins.set('fs', require('fs'));
```
