### ISSUE TITLE
hlx demo and hlx up no longer works

### ISSUE THREAD

**Issue by sometext** [adobe/helix-cli#1240]
**Description**
Getting started tutorial didn't work due to logger failure

**To Reproduce**
1.https://github.com/adobe/helix-home/blob/master/getting-started.md
2.
```
 hlx up
    __ __    ___
   / // /__ / (_)_ __
  / _  / -_) / /\ \ /
 /_//_/\__/_/_//_\_\ v6.1.1

Debugger listening on ws://127.0.0.1:9229/364e6c93-5c30-4cc7-a729-541232d3d90e
For help, see: https://nodejs.org/en/docs/inspector
Building project files...
Using @adobe/helix-pipeline version 6.1.1 from .hlx/build/node_modules/@adobe/helix-pipeline.
html (src/html.htl)
Building project files...done 75ms
[hlx] info: Starting helix-simulator v2.17.5
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
Note:
The project does not have a helix-config.yaml which is necessary to
access remote content and to deploy helix. Consider running
hlx up --save-config to generate a default config.
[41440] HTTP: listening on port 55028
[hlx] error: Exception during #00/use:fetch from /Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:62:
RangeError: Maximum call stack size exceeded
    at DerivedLogger.__ow_logger.log (/Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:1:1)
    at DerivedLogger.<computed> (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log (/Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.<computed> (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log (/Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.<computed> (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log (/Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.<computed> (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log (/Users/bmorrow/src/hackathon/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.<computed> (/usr/local/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
```

**Expected behavior**

**Screenshots**

**Version:**
run: `$ hlx --version`

6.1.1

**Additional context**
Resolved once I modified create-logger.js (95)
```
      //return self.log(level, ...args);
      return null;
```

**Comment by rofe** [comment]
I can confirm the issue. @tripodsan could you take a look?

**Comment by MarquiseRosier** [comment]
This is a pipeline issue with the backwards compatibility code. We set the property 
`__ow_logger.log` 
to an anonymous function. 

https://github.com/adobe/helix-pipeline/blob/35fd1679692844343a6c7e15ae69b2d220b2cfaa/src/utils/openwhisk.js#L131-L134

Later on, when logger.silly is called and it goes into DerivedLogger the last line where it calls self.log(level, ...args) has been redefined in the code above to matches the signature for the anonymous function.

https://github.com/winstonjs/winston/blob/319abf1c17e934595bd2e24a276f1e3d9f7cd709/lib/winston/create-logger.js#L91-L95

**Comment by rofe** [comment]
@koraa is this something you could help with?

**Comment by MarquiseRosier** [comment]
@rofe @koraa  I submitted a PR I'll link it to this page. It fixes the issue, i'm just waiting on everyone to review it and make sure we can safely toss out the compatibility code. 

https://github.com/adobe/helix-pipeline/pull/544

**Comment by rofe** [comment]
Thanks @MarquiseRosier! I didn't realize you would continue to look into this issue because you unassigned it 😄

**Comment by tripodsan** [comment]
tested with 

```
$ hlx --version
7.0.3
```

and it seems to work again.
