### ISSUE TITLE
Problems building helix due to missing crypto library

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#213]
```
$ npm install

> @adobe/nodegit@0.22.2-fork.1 install ./helix-cli/node_modules/@adobe/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: ./helix-cli/node_modules/@adobe/nodegit/vendor/libssh2/configure --with-libssl-prefix=./helix-cli/node_modules/@adobe/nodegit/vendor/openssl/openssl
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: './helix-cli/node_modules/@adobe/nodegit/vendor/libssh2/configure --with-libssl-prefix=./helix-cli/node_modules/@adobe/nodegit/vendor/openssl/openssl' }
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: ./helix-cli/node_modules/@adobe/nodegit/vendor/libssh2/configure --with-libssl-prefix=./helix-cli/node_modules/@adobe/nodegit/vendor/openssl/openssl
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '.helix-cli/node_modules/@adobe/nodegit/vendor/libssh2/configure --with-libssl-prefix=./helix-cli/node_modules/@adobe/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @adobe/nodegit@0.22.2-fork.1 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @adobe/nodegit@0.22.2-fork.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tripod/.npm/_logs/2018-09-25T01_01_02_674Z-debug.log
```

**Comment by tripodsan** [comment]
Tried:

```
$ rm -rf node_modules/ package-lock.json
$ npm install
```

--> same result

**Comment by tripodsan** [comment]
tried:

```
$ sudo xcode-select --install
```

--> same result

**Comment by tripodsan** [comment]
btw, where did we fork this nodegit from? because the upgrade to libssh1.8.0 is not in the original nodegit repo.

**Comment by tripodsan** [comment]
btw: I tried with xcode 10 and xcode 9.4.1

**Comment by kptdobe** [comment]
I had the same issue yesterday and running 
```
sudo xcode-select --install
rm -fr node_modules
npm install
```

worked for me.

**Comment by tripodsan** [comment]
not for me...I tried many times....

```
$ xcodebuild -version
Xcode 9.4.1
Build version 9F2000
```

**Comment by stefan-guggisberg** [comment]
> I figured that the upgrade to libssh 1.8.0 caused this problems.
> adobe/nodegit@640717c
> 
> when I revert this commit, nodegit builds again for me.

@tripodsan strange. since that commit doesn't affect the embedded `vendor/libssh` sources which are still 1.8.

**Comment by kptdobe** [comment]
```
Xcode 10.0
Build version 10A255
```

**Comment by tripodsan** [comment]
> @tripodsan strange. since that commit doesn't affect the embedded vendor/libssh sources which are still 1.8.

yes, but it changed the makefiles / configure script. I looked at the configure output more closely, and in both cases, `libssl` is not found. but with the 1.7.0 script, it detects `libgcrypt` and hence continues with the configuration. 

something in my system make it not find the libssl...maybe some other intallation I did....

**Comment by tripodsan** [comment]
ok. found a solution:

setting:
```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```
before running the build, works.
