### ISSUE TITLE
Seem to get an issue on OS X Mojave when trying to install via npm

### ISSUE THREAD

**Issue by joransky-xk** [adobe/helix-cli#220]
```
[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/openssl/openssl
/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/openssl/openssl' }
/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/joshuaoransky/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows
```

**Comment by davidnuescheler** [comment]
this was prompted by `npm i -g @adobe/helix-cli` to be precise, with v0.7.9 being the most recent release.

**Comment by tripodsan** [comment]
this has nothing to do with mojave, but with the latest nodegit.... @stefan-guggisberg already reverted nodegit, but we haven't released a new helix-cli. I will do shortly....

**Comment by tripodsan** [comment]
Well, we have released it, but it was not listed as release in github.
please try `0.7.11`

**Comment by stefan-guggisberg** [comment]
version 0.7.10 published on npm already includes this change (ie reverted
to nodegit 0.22.2).

**Comment by tripodsan** [comment]
latest version on npmjs is 0.7.11
https://www.npmjs.com/package/@adobe/helix-cli
