### ISSUE TITLE
[hlx deploy] fires an exception if no contentRepo has been set

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#227]
```
hlx demo test
hlx build
hlx deploy #set your fastly and Adobe IO credentials and ids...
```

fire exception: 

```
../@adobe/helix-cli/node_modules/yargs/yargs.js:1133
      else throw err
           ^

TypeError: Cannot read property 'contentRepo' of null
    at Function.getDefaultContentURL (../@adobe/helix-cli/src/deploy.cmd.js:53:16)
    at Object.builder (../@adobe/helix-cli/src/deploy.js:90:34)
    at Object.runCommand (../@adobe/helix-cli/node_modules/yargs/lib/command.js:183:35)
    at Object.parseArgs [as _parseArgs] (../@adobe/helix-cli/node_modules/yargs/yargs.js:1046:30)
    at Object.parse (../@adobe/helix-cli/node_modules/yargs/yargs.js:551:25)
    at CLI.run (../@adobe/helix-cli/src/cli.js:70:8)
    at Object.<anonymous> (../@adobe/helix-cli/index.js:19:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```

**Comment by tripodsan** [comment]
ah, this only happens if the `helix-config.yaml` is empty. then the `saveLoad()` returns `undefined`.
