### ISSUE TITLE
[hxl strain] fires an exception at the end of the process (sometimes)

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#259]
**To Reproduce**
Just run `hlx strain` and sometimes you get output logs:

```
All dicts have been updated.
🚀  Activated latest version, version 69 is live
✅  VCL helix.vcl has been updated
Unable to update VCL helix.vcl
422 - {"msg":"Version locked","detail":"Version '69' for service '3t7g8apsfQlFyvuHIQn9e8' is locked"}
(node:83077) UnhandledPromiseRejectionWarning: Error: Unable to update VCL helix.vcl
    at request.then.catch (/Users/alex/work/dev/helix/project-helix/modules/helix-cli/src/publish.cmd.js:495:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:83077) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:83077) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
💀  Purged entire cache
✅  All strains have been published and are online.
```

**Version:**
run: `$ hlx --version`
0.8.1-pre.2

**Comment by trieloff** [comment]
There seems to be a hard-to-reproduce condition where the update of the VCL sometimes happens after the version gets published.

**Comment by kptdobe** [comment]
Yes, but the reason and the fix is easy ;)
Working on the PR...
