### ISSUE TITLE
[hlx up] Uncaught exception in pre.js triggers an unclear error message

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#302]
**To Reproduce**
1. `hlx demo test`
2. `cd test`
3. Edit `src/html.pre.js` and just add line `throw new Error('this is an uncaught exception');` in the `pre` function
4. Save and run `hlx up`

When trying to load any page in the browser, you get a 500 but the error logs in the console say:

```
[hlx] error: Error while delivering resource /index.html - TypeError: reducedHtml.indexOf is not a function
    at findESIInclueTags (/Users/alex/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodesi/lib/esi.js:69:39)
    at processHtmlText (/Users/alex/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodesi/lib/esi.js:26:9)
    at Object.process (/Users/alex/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/nodesi/lib/esi.js:51:16)
    at Promise.resolve.then.then.then (/Users/alex/.nvm/versions/node/v8.12.0/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/petridish/src/HelixServer.js:117:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

Reason is that the processing is still going on and the ESI module receives a null body.

**Expected behavior**
The error message should say something like:

```
[hlx] error: Error while delivering resource /index.html - Error: this is an uncaught exception
```

I do not think https://github.com/adobe/hypermedia-pipeline/issues/81 addresses this issue.

**Version:**
run: `$ hlx --version`
0.8.0

**Comment by tripodsan** [comment]
with latest pipeline:
```
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[hlx] warn: tapping failed: Error: this is an uncaught exception
```
