### ISSUE TITLE
Feed the gap between `hlx init`and `hlx deploy`

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#33]
Run: 
```
hlx init
```

Edit the `helix-config.yaml` file and define the contentRepo url

```
hlx build
hlx deploy
```

-> Error

```
(node:38934) UnhandledPromiseRejectionWarning: OpenWhiskError: PUT https://runtime.adobe.io/api/v1/namespaces/acapt/actions/--dirty--html?overwrite=true Returned HTTP 400 (Bad Request) --> "The name of the entity contains illegal characters."
    at Client.handleErrors (/Users/alex/.nvm/versions/node/v9.11.2/lib/node_modules/@adobe/helix-cli/node_modules/openwhisk/lib/client.js:157:11)
    at rp.catch.err (/Users/alex/.nvm/versions/node/v9.11.2/lib/node_modules/@adobe/helix-cli/node_modules/openwhisk/lib/client.js:117:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:38934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Reason is the missing git remote for the "code" (no git remote repo) which is used as to generate the action name. 

cc @trieloff @tripodsan

**Comment by trieloff** [comment]
I assume you have all the auth parameters set?

`hlx deploy` tries to find out the name of the current remote. As you start without a remote in `hlx init`, it ends up being empty. The question is what to do now:

* set a value for not having a remote (`dirty--dirty`)
* reject `hlx deploy` until there is a remote
* create a GitHub repo in `init` and use it as remote

**Comment by kptdobe** [comment]
Ah genau... I got confused between the content and the code repo! I changed the description and turned the issue into a bug instead of an enhancement. 

Ok, it is definitively an enhancement.

Can't we just use the project name as a fallback ?

**Comment by trieloff** [comment]
I still think it's a bug. Maybe `local--${pwd}--` would be a good prefix.

**Comment by kptdobe** [comment]
pwd would "expose" your local file system structure. @tripodsan does not like it.

**Comment by trieloff** [comment]
I meant the directory name which should be identical to the project name. Putting `local` in front is what matters for me.

**Comment by kptdobe** [comment]
Local + directory name is fine. 
What's confusing is when you start adding your code to git, the action names will change (without removing the old ones). I cannot evaluate: what is the impact of polluting your space with multiple useless actions ?

**Comment by trieloff** [comment]
There should be no impact. Serverless functions don't cost anything when they don't run, and you will end up having many many functions (# of projects * # of refs * # of selectors * # of developers)

**Comment by kptdobe** [comment]
I tested the fix and I get now another error:
```
⏳  Deploying .hlx/build/html.js as local--mytestproject--dirty--html
⏳  Deploying .hlx/build/html.js as local--mytestproject--dirty--html
hlx deploy

Deploy packaged functions to Adobe I/O runtime

Deployment Options
  --auto           Enable auto-deployment   [boolean] [required] [default: true]
  --wsk-auth       Adobe I/O Runtime Authentication key      [string] [required]
  --wsk-namespace  Adobe I/O Runtime Namespace               [string] [required]
  --default        Adds a default parameter to the function              [array]
  --dirty          Allows deploying a working copy with uncommitted changes
                   (dangerous)                        [boolean] [default: false]

Advanced Options
  --wsk-host     Adobe I/O Runtime API Host
                                          [string] [default: "runtime.adobe.io"]
  --loggly-host  API Host for Log Appender
                                       [string] [default: "trieloff.loggly.com"]
  --loggly-auth  API Key for Log Appender ($HLX_LOGGLY_AUTH)
                                                          [string] [default: ""]
  --target, -o   Target directory for compiled JS
                                                [string] [default: ".hlx/build"]
  --docker       Docker image for Adobe I/O Runtime function
                                  [default: "trieloff/custom-ow-nodejs8:latest"]
  --prefix, -p   Prefix for the deployed action name.
                                      [default: "local--mytestproject--dirty--"]
  --content      Overrides the GitHub content URL         [string] [default: ""]

Options:
  --version           Show version number                              [boolean]
  --dry-run           List the actions that would be created, but do not
                      actually deploy                 [boolean] [default: false]
  --fastly-namespace  CDN Namespace (e.g. Fastly Service ID)            [string]
  --fastly-auth       API Key for Fastly API ($HLX_FASTLY_AUTH)
                                                          [string] [default: ""]
  --help              Show help                                        [boolean]

Error: Object argument required.
    at applyDefaults (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/object-hash/index.js:79:11)
    at objectHash (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/object-hash/index.js:31:13)
    at Function.exports.sha1 (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/object-hash/index.js:44:10)
    at Object.append (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/src/strain-config-utils.js:142:14)
    at DeployCommand.run (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/src/deploy.cmd.js:247:39)
    at Object.handler (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/src/deploy.js:118:10)
    at Object.runCommand (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/yargs/yargs.js:1046:30)
    at Object.parse (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/node_modules/yargs/yargs.js:551:25)
    at CLI.run (/Users/alex/work/dev/playground/project-helix/modules/helix-cli/src/cli.js:55:8)
```

**Comment by kptdobe** [comment]
I do not have one. I just ran `hlx init`, `hlx build`, `hlx deploy`. Do I need one ?

**Comment by trieloff** [comment]
`hlx build` should create one for you.

**Comment by trieloff** [comment]
It looks like you had an empty or invalid `.hlx/strains.yaml` and the strain config couldn't deal with that. dfea3ca should fix that and also create a good default config for you. (with the risk of overwriting existing strains)

**Comment by tripodsan** [comment]
@kptdobe is this still a problem?

**Comment by kptdobe** [comment]
Tricky question... ;)
There is no error or exception, thus let's say no pb anymore. 
The follow up ticket for the things to improve would be: https://github.com/adobe/project-helix/issues/326
