### ISSUE TITLE
unexpected errors in actions

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-cli#387]
```
    "2018-12-13T20:34:28.658595336Z stderr: Error during initialization: { Error: Cannot find module 'uuid/v4'",
    "2018-12-13T20:34:28.658650182Z stderr: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)",
    "2018-12-13T20:34:28.65865457Z  stderr: at Function.Module._load (internal/modules/cjs/loader.js:507:25)",
    "2018-12-13T20:34:28.658657734Z stderr: at Module.require (internal/modules/cjs/loader.js:637:17)",
    "2018-12-13T20:34:28.658660992Z stderr: at require (internal/modules/cjs/helpers.js:20:18)",
    "2018-12-13T20:34:28.658664003Z stderr: at Object.<anonymous> (/nodejsAction/XXjlkhnn/node_modules/jsdom/node_modules/request/lib/auth.js:4:12)",
    "2018-12-13T20:34:28.658667661Z stderr: at Module._compile (internal/modules/cjs/loader.js:689:30)",
    "2018-12-13T20:34:28.658670746Z stderr: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)",
    "2018-12-13T20:34:28.658673841Z stderr: at Module.load (internal/modules/cjs/loader.js:599:32)",
    "2018-12-13T20:34:28.658676903Z stderr: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)",
    "2018-12-13T20:34:28.658680052Z stderr: at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }"
```

**Comment by stefan-guggisberg** [comment]
fixed via #388
