### ISSUE TITLE
Published HTML Action returns {}

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-cli#408]
Deploy with `hlx` master, then:

```bash
$ http https://www.primordialsoup.life/index.html X-Debug:true
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept, User-Agent
Access-Control-Allow-Methods: OPTIONS, GET, DELETE, POST, PUT, HEAD, PATCH
Access-Control-Allow-Origin: *
Age: 391
Cache-Control: max-age=604800, public
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 24
Content-Type: application/json
Date: Wed, 19 Dec 2018 11:28:28 GMT
Perf-Br-Resp-Out: 1545218517.278
Server: api-gateway/1.9.3.1
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: X-Debug, X-Strain
Via: 1.1 varnish
X-Action-Root: /trieloff/default/https---github-com-trieloff-helix-demo-git--master--
X-Backend-Name: 3l2MjGcHgWw5NUJz7OKYH3--F_AdobeRuntime
X-Backend-URL: /api/v1/web/trieloff/default/https---github-com-trieloff-helix-demo-git--master--html?owner=trieloff&repo=helix-demo&ref=&path=/index.md&selector=&extension=html&strain=default&params=(null)
X-CDN-Request-ID: aeea1c38-be21-4aae-bea2-14d4c20e63d6
X-Cache: HIT
X-Cache-Hits: 1
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-GW-Cache: MISS
X-Github-Static-Ref: @(null)
X-Request-ID: HGbphp8qm8kiyKg55YvfCyQLy2nLuHN3
X-Root-Path:
X-Served-By: cache-hhn1543-HHN
X-Strain: default
X-Timer: S1545218908.061127,VS0,VE4
X-Trace: vcl_recv; hlx_headers_recv; hlx_backend_recv; hlx_strain; hlx_block_recv; hlx_deny; hlx_allow; hlx_recv_pipeline; hlx_owner; hlx_repo; hlx_ref; hlx_root_path; hlx_action_root; vcl_deliver; hlx_headers_deliver
X-URL: /index.html
X-Version: 974; src=974; cli=0.10.12-pre.1; rev=cfc821c0d3590fc7630cb90bd4694c0beab656a5
X-XSS-Protection: 1; mode=block
x-openwhisk-activation-id: 4fb02cc26ec345cfb02cc26ec345cfcb

{}
```

The only response is `{}` and the status code is (incorrectly) 200.

```bash
wsk activation result 4fb02cc26ec345cfb02cc26ec345cfcb
{
    "body": {},
    "headers": {
        "Content-Type": "application/json"
    },
    "statusCode": 200
}
```

```bash
wsk activation logs 4fb02cc26ec345cfb02cc26ec345cfcb
2018-12-19T11:21:57.221Z       stdout: debug: Constructing HTML Pipeline
2018-12-19T11:21:57.221Z       stdout: debug: Creating pipeline
2018-12-19T11:21:57.223Z       stdout: debug: initializing ajv {"useDefaults":true,"coerceTypes":true}
2018-12-19T11:21:57.256Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/action  (action.schema.json)
2018-12-19T11:21:57.257Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/content  (content.schema.json)
2018-12-19T11:21:57.258Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/context  (context.schema.json)
2018-12-19T11:21:57.259Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/mdast  (mdast.schema.json)
2018-12-19T11:21:57.259Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/meta  (meta.schema.json)
2018-12-19T11:21:57.260Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/position  (position.schema.json)
2018-12-19T11:21:57.261Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/rawrequest  (rawrequest.schema.json)
2018-12-19T11:21:57.261Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/request  (request.schema.json)
2018-12-19T11:21:57.262Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/response  (response.schema.json)
2018-12-19T11:21:57.263Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/secrets  (secrets.schema.json)
2018-12-19T11:21:57.263Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/section  (section.schema.json)
2018-12-19T11:21:57.264Z       stdout: debug: - https://ns.adobe.com/helix/pipeline/textcoordinates  (textcoordinates.schema.json)
2018-12-19T11:21:57.264Z       stdout: debug: ajv initialized
2018-12-19T11:21:57.264Z       stdout: debug: Coercing secrets
2018-12-19T11:21:57.267Z       stdout: debug: Running HTML pipeline

```

**Comment by trieloff** [comment]
With adobe/openwhisk-loggly-wrapper#13 in the books, we get some additional log output:

```
2018-12-19T11:58:48.525Z       stdout: silly: resolved {"result":{"error":"\nTypeError: Cannot read property '__OW_ACTIVATION_ID' of null\nTypeError: Cannot read property '__OW_ACTIVATION_ID' of null"},"request":"debug","activation":"d005cc592dea4cea85cc592dea7cea48","function":"https---github-com-trieloff-helix-demo-git--master--html"}
```

**Comment by trieloff** [comment]
With more error logging in the pipeline:

```
TypeError: Cannot read property '__OW_ACTIVATION_ID' of null (TypeError: Cannot read property '__OW_ACTIVATION_ID' of null
    at Object.get [as __OW_ACTIVATION_ID] (/nodejsAction/src/service.js:251:60)
    at production (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/utils/is-production.js:18:50)
    at pipe.every.when (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:42:30)
    at wrappedfunc (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/pipeline.js:159:24)
    at tapresults._taps.map (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/pipeline.js:303:29)
    at Array.map (<anonymous>)
    at merge (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/pipeline.js:301:37)
    at piperesult.filter.reduce (/nodejsAction/XXDPCCdJ/node_modules/@adobe/helix-pipeline/src/pipeline.js:339:43)
    at process._tickCallback (internal/process/next_tick.js:68:7))})
```

**Comment by trieloff** [comment]
`curl http "https://adobeioruntime.net/api/v1/web/trieloff/default/https---github-com-trieloff-helix-demo-git--master--html?owner=trieloff&repo=helix-demo&ref=master&path=/index.md&selector=&extension=html&strain=default&params=(null)"`

Is now giving me the results I need. Bug tally:

- https://github.com/adobe/helix-pipeline/issues/142 *required*
- https://github.com/adobe/openwhisk-loggly-wrapper/issues/12 nice to have
- https://github.com/adobe/helix-pipeline/issues/145 unrelated
- adobe/helix-pipeline#129 would be nice to have, too

**Comment by kptdobe** [comment]
Is there a workaround ? I hit the same issue with https://www.project-helix.io/

**Comment by kptdobe** [comment]
Not sure if this is related or this helps but my `hlx publish` tells me things like:

```
Publishing [=================---------------------------------] content repo 3.7serror: Unknown error when deleting key pipeline from dictionary 76zAmANbgcjcLzZKUoMdds
Publishing [==================--------------------------------] content root 4.0serror: Unknown error when deleting key client from dictionary 3sS24mCQMaOri4jxb7Sfiv
Publishing [===================-------------------------------] static ref 3.8serror: Unknown error when deleting key default from dictionary 5b3CsBSMnnU4lmAbuEP6Br
Publishing [====================------------------------------] whitelist 3.5serror: Unknown error when deleting key default from dictionary 76zAmANbgcjcLzZKUoMdds
Publishing [=====================-----------------------------] content root 3.3serror: Unknown error when deleting key pipeline from dictionary 5b3CsBSMnnU4lmAbuEP6Br
Publishing [=====================-----------------------------] whitelist 3.2serror: Unknown error when deleting key pipeline from dictionary 3sS24mCQMaOri4jxb7Sfiv
Publishing [========================================----------] Uploading VCL strains.vcl 0.8serror: Unknown error when deleting key pipeline from dictionary 2Z9mTIWxezCtyoF3Q1l5ml
Publishing [========================================----------] blacklist 0.7serror: Unknown error when deleting key client from dictionary 5b3CsBSMnnU4lmAbuEP6Br
Publishing [=========================================---------] whitelist 0.7serror: Unknown error when deleting key default from dictionary 3sS24mCQMaOri4jxb7Sfiv
Publishing [===========================================-------] static ref 0.5serror: Unknown error when deleting key client from dictionary 2Z9mTIWxezCtyoF3Q1l5ml
Publishing [============================================------] blacklist 0.5serror: Unknown error when deleting key client from dictionary 76zAmANbgcjcLzZKUoMdds
Publishing [============================================------] content root 0.4serror: Unknown error when deleting key default from dictionary 2Z9mTIWxezCtyoF3Q1l5ml
Publishing [==================================================] Uploading VCL dynamic.vcl 0.0s
Publishing [==================================================] Uploaded VCL helix.vcl 0.0s
```

**Comment by kptdobe** [comment]
Interestingly, I am using v0.10.15 when I get the {}. But this morning I do not get it anymore, I just get a 404. Need to debug now.
