### ISSUE TITLE
helix 2.0+ publish broken for developer.adobe.com

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-cli#835]
**Description**
Cannot `hlx publish` since helix-cli 2.0.0. Tried both 2.0.0 and 2.0.3.

You can see the failures in these two CD runs:

w/ helix-cli@2.0.0: https://circleci.com/gh/adobe/developer.adobe.com/1690
w/ helix-cli@2.0.3: https://circleci.com/gh/adobe/developer.adobe.com/1835

The error is:

```
> hlx publish

Publishing [] preparing fastly transaction 0.0sPublishing [] preparing service config for Helix 6.1sPublishing [] failed to set service config up for Helix 1.2serror: Remote publish service failed StatusCodeError: 500 - {"message":"FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 116 }'","stack":["FastlyError: Couldn't find Backend '{ deleted => 0000-00-00 00:00:00, name => Proxywwwadobeio3a0a, service => 0gDEZCgYFsF773b88iAgvS, version => 116 }'","    at request.then (/nodejsAction/XXKbgecJ/node_modules/@adobe/fastly-native-promises/src/httpclient.js:100:17)","    at process._tickCallback (internal/process/next_tick.js:68:7)"],"status":"error"}
error: Error while running the Publish command: Error: Unable to setup service config
    at request.post.then.catch (/home/circleci/project/node_modules/@adobe/helix-cli/src/remotepublish.cmd.js:188:13)
```

**Comment by tripodsan** [comment]
it seems the backend of the proxy isn't updated:
```
Undefined `backend F_Proxywwwadobeio3a0a`
at: (input Line 1418 Pos 21)
  set req.backend = F_Proxywwwadobeio3a0a;
--------------------#####################-
```

**Comment by tripodsan** [comment]
the backend name computation in helix-shared changed recently (was fixed :-). but apparently, `helix-publish` doesn't want to update the backend for some reason. weird.

**Comment by tripodsan** [comment]
@trieloff I looked at this problem for a long time, and I don't understand why the backend is not updated with the new name. AFAIU, the config json transferred from cli to helix-publish should have a stable `origin.name`, and the backends should be created accordingly. unless fastly doesn't want to create a 2nd backend entry for the same host....

**Comment by tripodsan** [comment]
I think what happens is that it exceeds max backends:

1. first tries to [create](https://github.com/adobe/fastly-native-promises/blob/v1.9.1/src/index.js#L139) a new backend for the new name, but receives:
```
{
    "msg": "Bad request",
    "detail": "Exceeding max_backends: 5"
}
```
2. then tries to update the existing backend and also fails.

the only weird thing is, that it doesn't fail publish alltogether, but only when activating the version.

quick workaround would probably be to delete the backend manually before activating it.
but the max backend limit might be a problem....

https://docs.fastly.com/guides/debugging/resource-limits#service-domain-and-origin-limits
