### ISSUE TITLE
[Regression] hlx publish shows a weird "Expected a string" error

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#846]
`hlx publish` does not work anymore. Simply run `hlx publish` in an existing project (ideally one you already published) and you get exactly: 

```
$  hlx publish --log-level silly
Expected a string
```

**Version:**
run: `$ hlx --version`
2.1.1

**Comment by trieloff** [comment]
Happens with a clean environment when running `node index.js publish --wsk-auth foo --wsk-namespace bar --fastly-namespace blub`

**Comment by kptdobe** [comment]
Running `hlx publish --exclude foobar` goes to next steps but ends up with error:

```
Publishing [====----------------------------------------------] preparing service config for Helix 16.1serror: Error while running the Publish command: TreeOrBlobNotFoundError: No file or directory found at "e897c8e2c305a0c838e6042e8c817af64fcf4bc6:helix-config.yaml".
    at resolveFile (/Users/alex/.nvm/versions/node/v10.15.3/lib/node_modules/@adobe/helix-cli/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:7261:9)
    at Object.readObject$1 [as readObject] (/Users/alex/.nvm/versions/node/v10.15.3/lib/node_modules/@adobe/helix-cli/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:7182:21)No file or directory found at "e897c8e2c305a0c838e6042e8c817af64fcf4bc6:helix-config.yaml".
Error while running the Publish command
```

**Comment by tripodsan** [comment]
the first error is caused here, I think:
https://github.com/adobe/helix-cli/blob/f2897185bbb7660c3b11c35ef828ee85912b824b/src/remotepublish.cmd.js#L120

**Comment by trieloff** [comment]
Waiting for #849
